# Site settings
title: "ADVOCODO - Tiny Digital Agency"
description: "ADVOCODO - Tiny Digital Agency"
#baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://advocodo.com"
#url: "http://localhost:3000" # the base hostname & protocol for your site

# User settings
username: "ADVOCODO"
logo: '<img src="https://avatars.githubusercontent.com/u/19282864" alt="ADVOCODO">'
user_description: "Plus de 10 ans dâ€™xp en PHP dans lâ€™e-commerce avec du Symfony, du Magento, du WooCommerce.<br>
<br>
Lancement de webshop de 0 Ã  1 avec intervention sur toute la stack technique, ou renfort dans des Ã©quipes tech sur des sujets prÃ©cis.<br>
<br>
Ã€ votre disposition pour Ã©tudier vos besoins."
user_title: "ğğ‡ğ ğƒğğ¯ğğ¥ğ¨ğ©ğğ« ğŸ¤–<br>Magento - Symfony"
email: "uryyb@nqibpbqb.pbz"
linkedin_username: "advocodo"
github_username: "advocodo"
twitter_username: "ADVOCODO"

# Google-analytics
google-analytics:
  id: "G-ESSEN3K0ZZ"

exclude: ['package.json', 'src' , 'node_modules']
